version: '3'

services:
  app:
    build: ./app
    ports:
      - 5000:5000
    restart: on-failure
    depends_on:
      - selenium
      - mysql
    links:
      - mysql

  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
      - 7900:7900
    restart: always
  
  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dbadmin
      MYSQL_PASSWORD: dbadmin
      TZ: Asia/Taiwan
      MYSQL_ROOT_HOST: '%'
      MYSQL_ALLOW_EMPTY_PASSWORD: false 
      MYSQL_DATABASE: lsa2    
  
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: web_phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    links:
      - mysql
    restart: always