version: '3'

services:
  app:
    build: ./app
    ports:
      - 5000:5000
    depends_on:
      - selenium
    links:
      - mysql
  
  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
      - 7900:7900
    restart: always
  
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3300:3300
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Taiwan
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: web_phpmyadmin
    ports:
      - 8080:80
    environment:
      # - PMA_ARBITRART = 1
      - PMA_HOST=mysql
      # - PMA_USER=root
      # - PMA_PASSWORD=12345678
    links:
      - mysql
    restart: always