version: '3'

services:
  app:
    build: ./app
    ports:
      - 5000:5000
    depends_on:
      - selenium
    links:
      - mysql

  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
      - 7900:7900
    restart: always
  
  mysql:
    image: mysql/mysql-server:5.7
    # build: ./app
    restart: always
    ports:
      - 3300:3300
    environment:
      # MYSQL_ROOT_USER: root
      MYSQL_ROOT_HOST: '%'
      # MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dbadmin
      MYSQL_PASSWORD: dbadmin
      MYSQL_DATABASE: lsa2    
      TZ: Asia/Taiwan
    volumes:
      # - db-data:/var/lib/mysql
      - ./db/:/docker-entrypoint-initdb.d/:ro
  
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: web_phpmyadmin
    ports:
      - 8080:80
    environment:
      # - PMA_ARBITRART = 1
      - PMA_HOST=mysql
      # - PMA_USER=root
      # - PMA_PASSWORD=12345678
    links:
      - mysql
    restart: always